### PR TITLE
7.4.1

### PR DESCRIPTION
**Pull request by Kylmakalle**

### CODE REVIEW

**Comment by Salman789597** [comment]
block my telegram acount 00966544729412

**Comment by Kylmakalle** [comment]
> block my telegram acount 00966544729412

Not Nicegram desire.
Delete via official TG site
https://my.telegram.org/auth

**Review by Salman789597 — COMMENTED** [review]
telegram unsubcrib

**Review by Kasbr305 — COMMENTED** [review]
G

**Comment by Kasbr305** [comment]
>

**Pull request merged**
